name: ConfigureVariable

on:
  workflow_dispatch:
   inputs:
      environment:
        type: choice
        description: Environment
        required: true
        options:
          - dev
          - staging
          - prod
          - qa

      version:
         description:  "Dcoker version"
         required: true

env:
  name: satya

jobs:
  say-hello:
    runs-on: ubuntu-latest
    env:
      lastname: vanga
    steps:
      - run: echo "Hi"
      - run: echo "$name and ${{ secrets.PIN }} and ${{ vars.PLACE }}"
      - run: echo "github metadata data  ${{ github.repository }} ${{ github.repository_owner }} ${{ github.actor }} ${{ github.ref }}"

        
